name: SimpleManhunt
version: '${project.version}'
main: com.imabanana80.simplemanhunt.SimpleManhunt
api-version: '1.20'
authors: [Imabanana80]
description: A super simple minecraft manhunt plugin
commands:
  runner:
    description: Check who the runner currently is
  setrunner:
    description: Set the runner
    permission: SimpleManhunt.manage
  hunters:
    description: Check who the hunters currently are
  addhunter:
    description: Add a hunter
    permission: SimpleManhunt.manage
  removehunter:
    description: Remove a hunter
    permission: SimpleManhunt.manage
  tracker:
    description: Give yourself a tracker
